services:
  harmony-link:
    image: harmonyai/harmony-link:latest
    pull_policy: always
    env_file: ./harmony-link/.env
    ports:
      - "28080:28080"
      - "28081:28081"
    volumes:
      - .:/quickstart
      - ./harmony-link/harmony-tmp:/app/harmony-tmp
      - ./harmony-link/config.json:/app/config.json
      - ./harmony-link/harmony-user.key:/app/harmony-user.key
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HARMONY_LINK_CONTAINER_MODE=1
    networks:
      - harmony-link-network

  harmony-link-ui:
    image: harmonyai/harmony-link-ui:latest
    pull_policy: always
    ports:
      - "8080:80"
    networks:
      - harmony-link-network

networks:
  harmony-link-network:
    name: harmony-link-network
    driver: bridge
