services:
  harmony-link:
    image: harmonyai/harmony-link:latest
    pull_policy: always
    env_file: ./harmony-link/.env
    ports:
      - "28080:28080"
      - "28081:28081"
    volumes:
      - ./harmony-link/harmony-tmp:/app/harmony-tmp
      - ./harmony-link/config.json:/app/config.json
      - ./harmony-link/harmony-user.key:/app/harmony-user.key
      - /var/run/docker.sock:/var/run/docker.sock
      # ATTENTION FOR RUNNING DOCKERIZED
      # This path mounts the quickstart repo on a path matching the host path
      # The path needs to match the exact path on the host, so docker compose for the integrations works correctly
      # and relative path mounts will be resolved properly.
      # For WSL this requires a special mount path starting with "/run/desktop/mnt/host/",
      # followed by the actual path on the host machine, e.g. "d/projects/quickstart"
      # also see comments in ./harmony-link/.env file.
      - /run/desktop/mnt/host/d/projects/quickstart:/run/desktop/mnt/host/d/projects/quickstart
    environment:
      - HARMONY_LINK_CONTAINER_MODE=1
    networks:
      - harmony-link-network

  harmony-link-ui:
    image: harmonyai/harmony-link-ui:latest
    pull_policy: always
    ports:
      - "8080:80"
    networks:
      - harmony-link-network

networks:
  harmony-link-network:
    external: true
    name: harmony-link-network
